#!/usr/bin/env python

import inventory_remove
import inventory_add
import inventory_modifyexpiry
import inventory_modifyname
import inventory_daily
import inventory_printout
import inventory_addname
import yaml

import argparse

parser = argparse.ArgumentParser(description='Read and store product information from upc codes.')
parser.add_argument('action', action='store', help='The action we want to perform; can be one of: add, addmanually, modifyexpiry, modifyname, remove, printout, or daily. Select add to begin!')

args = parser.parse_args()
#print args.accumulate(args.integers)
print "You have selected \"" + args.action + "\"."

print "Trying to read config file"
try:
	with open("profile.txt", "r") as f:
		config = yaml.safe_load(f)
except OSError:
	print "Can't open config file. Are you sure you ran opulate.py ?"
	raise


{'add' : inventory_add.main, 'addmanually' : inventory_addname.main, 'modifyexpiry' : inventory_modifyexpiry.main, 'modifyname' : inventory_modifyname.main, 'daily' : inventory_daily.main, 'remove' : inventory_remove.main, 'printout' : inventory_printout.main}[args.action]()

